# ViewResolver
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp


spring:
  datasource:
    #    url: jdbc:mysql://nicekkong.com:3306/trdev?serverTimezone=UTC&characterEncoding=UTF-8&verifyServerCertificate=false&useSSL=false
    url: jdbc:mariadb://nicekkong.com:3306/mydev
    username: myuser
    password: myuser!@
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    tomcat:
      validation-query: select 1 from dual
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      initial-size: 2
      max-active: 2
      max-idle: 2
      min-idle: 2
      max-wait: 5000
      time-between-eviction-runs-millis: 5000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none  # create, update, ...
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    #    database: mysql
    #    database-platform:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect
        show-sql: true
        format_sql: true
        use_sql_comments: true

  # ehcache 설정
  cache:
    jcache:
      config: classpath:ehcache/ehcache-${spring.config.activate.on-profile}.xml


# logback 설정
logging:
  config: classpath:logback/logback-${spring.config.activate.on-profile}.xml





default-email: default-nicekkong.com

