# 쿼리 파라메터 String 전체에 맵핑되어 보여준다. p6spy plugin
decorator:
  datasource:
    p6spy:
      enable-logging: true # 상용에선 false로 설정하여 사용한다.

email: local-nicekkong.com

spring:
  config:
    activate:
      on-profile: local

# https://meetup.toast.com/posts/149
#logging:
#  level:
#    root: debug
#    org.springframework: trace
#

